-- Seed OPCIONAL de bienes CBAM típicos (cemento y hierro/acero) con códigos CN (Anexo I, Reg. UE 2023/956).
-- Idempotente por (cn_code, name). Correr DESPUÉS de 002_cbam.sql.

insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2507 00 80', 'Arcillas calcinadas', 'cemento', 'Arcillas calcinadas', null, 't', 0, true where not exists (select 1 from cbam_goods where cn_code='2507 00 80' and name='Arcillas calcinadas');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2523 10 00', 'Clinker de cemento Portland', 'cemento', 'Clinker de cemento', null, 't', 1, true where not exists (select 1 from cbam_goods where cn_code='2523 10 00' and name='Clinker de cemento Portland');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2523 21 00', 'Cemento Portland blanco', 'cemento', 'Cemento', null, 't', 2, true where not exists (select 1 from cbam_goods where cn_code='2523 21 00' and name='Cemento Portland blanco');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2523 29 00', 'Cemento Portland (los demás)', 'cemento', 'Cemento', null, 't', 3, true where not exists (select 1 from cbam_goods where cn_code='2523 29 00' and name='Cemento Portland (los demás)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2523 30 00', 'Cemento aluminoso', 'cemento', 'Cementos aluminosos', null, 't', 4, true where not exists (select 1 from cbam_goods where cn_code='2523 30 00' and name='Cemento aluminoso');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2523 90 00', 'Otros cementos hidráulicos', 'cemento', 'Cemento', null, 't', 5, true where not exists (select 1 from cbam_goods where cn_code='2523 90 00' and name='Otros cementos hidráulicos');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '2601 12 00', 'Minerales de hierro aglomerados (sínter)', 'hierro_acero', 'Mineral sinterizado', null, 't', 6, true where not exists (select 1 from cbam_goods where cn_code='2601 12 00' and name='Minerales de hierro aglomerados (sínter)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7201 10 00', 'Arrabio sin alear (pig iron)', 'hierro_acero', 'Arrabio (pig iron)', 'Alto horno (BF)', 't', 7, true where not exists (select 1 from cbam_goods where cn_code='7201 10 00' and name='Arrabio sin alear (pig iron)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7203 10 00', 'Hierro de reducción directa (DRI)', 'hierro_acero', 'Hierro de reducción directa (DRI)', 'Reducción directa', 't', 8, true where not exists (select 1 from cbam_goods where cn_code='7203 10 00' and name='Hierro de reducción directa (DRI)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7206 10 00', 'Acero crudo en lingotes (sin alear)', 'hierro_acero', 'Acero crudo', 'BOF / EAF', 't', 9, true where not exists (select 1 from cbam_goods where cn_code='7206 10 00' and name='Acero crudo en lingotes (sin alear)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7207 11 00', 'Semiacabados de acero (palanquilla)', 'hierro_acero', 'Productos de hierro o acero', null, 't', 10, true where not exists (select 1 from cbam_goods where cn_code='7207 11 00' and name='Semiacabados de acero (palanquilla)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7213 91 10', 'Alambrón con muescas para hormigón armado', 'hierro_acero', 'Productos de hierro o acero', null, 't', 11, true where not exists (select 1 from cbam_goods where cn_code='7213 91 10' and name='Alambrón con muescas para hormigón armado');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7214 20 00', 'Barras de refuerzo para hormigón (rebar)', 'hierro_acero', 'Productos de hierro o acero', null, 't', 12, true where not exists (select 1 from cbam_goods where cn_code='7214 20 00' and name='Barras de refuerzo para hormigón (rebar)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7208 39 00', 'Chapa laminada en caliente, en bobinas', 'hierro_acero', 'Productos de hierro o acero', null, 't', 13, true where not exists (select 1 from cbam_goods where cn_code='7208 39 00' and name='Chapa laminada en caliente, en bobinas');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7216 33 00', 'Perfiles H laminados en caliente (estructurales)', 'hierro_acero', 'Productos de hierro o acero', null, 't', 14, true where not exists (select 1 from cbam_goods where cn_code='7216 33 00' and name='Perfiles H laminados en caliente (estructurales)');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7306 30 00', 'Tubos de acero soldados, sección circular', 'hierro_acero', 'Productos de hierro o acero', null, 't', 15, true where not exists (select 1 from cbam_goods where cn_code='7306 30 00' and name='Tubos de acero soldados, sección circular');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7318 15 00', 'Tornillos y pernos de acero', 'hierro_acero', 'Productos de hierro o acero', null, 't', 16, true where not exists (select 1 from cbam_goods where cn_code='7318 15 00' and name='Tornillos y pernos de acero');
insert into cbam_goods (cn_code, name, sector, aggregated_category, production_route, default_unit, sort, activo) select '7326 90 98', 'Las demás manufacturas de hierro o acero', 'hierro_acero', 'Productos de hierro o acero', null, 't', 17, true where not exists (select 1 from cbam_goods where cn_code='7326 90 98' and name='Las demás manufacturas de hierro o acero');
